// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: stcmsg.proto

package proto

import (
	proto "github.com/openconfig/ondatra/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgTopology struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interfaces []*proto.InterfaceConfig `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Lags       []*proto.Lag             `protobuf:"bytes,2,rep,name=lags,proto3" json:"lags,omitempty"`
}

func (x *MsgTopology) Reset() {
	*x = MsgTopology{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stcmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTopology) ProtoMessage() {}

func (x *MsgTopology) ProtoReflect() protoreflect.Message {
	mi := &file_stcmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTopology.ProtoReflect.Descriptor instead.
func (*MsgTopology) Descriptor() ([]byte, []int) {
	return file_stcmsg_proto_rawDescGZIP(), []int{0}
}

func (x *MsgTopology) GetInterfaces() []*proto.InterfaceConfig {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *MsgTopology) GetLags() []*proto.Lag {
	if x != nil {
		return x.Lags
	}
	return nil
}

type MsgTraffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flows []*proto.Flow `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
}

func (x *MsgTraffic) Reset() {
	*x = MsgTraffic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stcmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTraffic) ProtoMessage() {}

func (x *MsgTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_stcmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTraffic.ProtoReflect.Descriptor instead.
func (*MsgTraffic) Descriptor() ([]byte, []int) {
	return file_stcmsg_proto_rawDescGZIP(), []int{1}
}

func (x *MsgTraffic) GetFlows() []*proto.Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

var File_stcmsg_proto protoreflect.FileDescriptor

var file_stcmsg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x74, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x74, 0x63, 0x6d, 0x73, 0x67, 0x1a, 0x09, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x69, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x12, 0x38, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6e, 0x64, 0x61, 0x74, 0x72, 0x61, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x6e, 0x64, 0x61, 0x74,
	0x72, 0x61, 0x2e, 0x4c, 0x61, 0x67, 0x52, 0x04, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x31, 0x0a, 0x0a,
	0x4d, 0x73, 0x67, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x12, 0x23, 0x0a, 0x05, 0x66, 0x6c,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x6e, 0x64, 0x61,
	0x74, 0x72, 0x61, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6f, 0x6e, 0x64, 0x61, 0x74, 0x72, 0x61,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x74, 0x63, 0x61, 0x74, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stcmsg_proto_rawDescOnce sync.Once
	file_stcmsg_proto_rawDescData = file_stcmsg_proto_rawDesc
)

func file_stcmsg_proto_rawDescGZIP() []byte {
	file_stcmsg_proto_rawDescOnce.Do(func() {
		file_stcmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_stcmsg_proto_rawDescData)
	})
	return file_stcmsg_proto_rawDescData
}

var file_stcmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stcmsg_proto_goTypes = []interface{}{
	(*MsgTopology)(nil),           // 0: stcmsg.MsgTopology
	(*MsgTraffic)(nil),            // 1: stcmsg.MsgTraffic
	(*proto.InterfaceConfig)(nil), // 2: ondatra.InterfaceConfig
	(*proto.Lag)(nil),             // 3: ondatra.Lag
	(*proto.Flow)(nil),            // 4: ondatra.Flow
}
var file_stcmsg_proto_depIdxs = []int32{
	2, // 0: stcmsg.MsgTopology.interfaces:type_name -> ondatra.InterfaceConfig
	3, // 1: stcmsg.MsgTopology.lags:type_name -> ondatra.Lag
	4, // 2: stcmsg.MsgTraffic.flows:type_name -> ondatra.Flow
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_stcmsg_proto_init() }
func file_stcmsg_proto_init() {
	if File_stcmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stcmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgTopology); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stcmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgTraffic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stcmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stcmsg_proto_goTypes,
		DependencyIndexes: file_stcmsg_proto_depIdxs,
		MessageInfos:      file_stcmsg_proto_msgTypes,
	}.Build()
	File_stcmsg_proto = out.File
	file_stcmsg_proto_rawDesc = nil
	file_stcmsg_proto_goTypes = nil
	file_stcmsg_proto_depIdxs = nil
}
